---
driver:
  name: vagrant
  provider:
    name: libvirt
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: ubuntu18
    box: generic/ubuntu1804
    cpus: 2
    memory: 1024
    groups:
      - k8s-cluster
      - kube-master
      - etcd
      - kube-node
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../../../
  config_options:
    defaults:
      callback_whitelist: profile_tasks
  lint:
    name: ansible-lint
    options:
      c: .ansible-lint
  inventory:
    host_vars:
      ubuntu18:
        ansible_become: true
verifier:
  name: testinfra
  lint:
    name: flake8
